{
 "title": "Streamflow at Gage Locations",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "gageid", "label": "USGS Gage ID", "query": "SELECT gage_id from stats;" }
  ]
 },
 "panels": [
  {
   "title": "Streamflow at $gageid",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "repeat": "gageid",
   "fieldConfig": { "defaults": { "unit": "flowcms" } },
   "targets": [
    { "queryText": "SELECT * FROM '$gageid';", "rawQueryText": "SELECT * FROM '$gageid';" }
   ]
  },
  {
   "title": "KGE NSE PBIAS",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT * FROM stats where gage_id = \"$gageid\";--- and source=\"ngen\";",
     "rawQueryText": "SELECT * FROM stats where gage_id = \"$gageid\";--- and source=\"ngen\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Gages in your hydrofabric",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "queryText": "SELECT \n    hl.hl_uri,\n    (rt.minx + rt.maxx) / 2 AS lon,\n    (rt.miny + rt.maxy) / 2 AS lat\nFROM \n    hydrolocations hl\nJOIN \n    rtree_hydrolocations_geom rt ON hl.fid = rt.id\nWHERE \n    hl.hl_reference = 'Gages';",
     "rawQueryText": "SELECT \n    hl.hl_uri,\n    (rt.minx + rt.maxx) / 2 AS lon,\n    (rt.miny + rt.maxy) / 2 AS lat\nFROM \n    hydrolocations hl\nJOIN \n    rtree_hydrolocations_geom rt ON hl.fid = rt.id\nWHERE \n    hl.hl_reference = 'Gages';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}